### ISSUE TITLE
Erreur de landmark "nav" != "navigation"

### ISSUE THREAD

**Issue by raphaelgoetter** [DISIC/guide-integrateur#3]
Bonjour (et bravo pour ce document),

J'ai constaté une petite erreur de nommage dans le choix d'un landmark ARIA sur la fiche de Gabarit Général (peut-être ailleurs également) : https://github.com/DISIC/guide-integrateur/blob/master/1-gabarit-general.md

Dans la section "Éléments HTML5 et landmarks ARIA", il est indiqué : 

> la navigation principale et les éventuelles navigations secondaires : `role="nav"`.

La bonne valeur est `role="navigation"`

Bonne journée.

**Comment by flexbox** [comment]
Hello there!
J'ai vérifié partout et il n'y a le problème que dans cette section.

Fixed with https://github.com/DISIC/guide-integrateur/pull/8 🚀

**Comment by Etat-Plateforme** [comment]
Merci pour cette alerte. Nous avons vérifié et corrigée les sections non conformes cf. fixes #4 et #5.
